apiVersion: v1
kind: Service
metadata:
  name: practitioner-site-oh-mysql-srv
  labels:
    app: practitioner-site-oh-mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: practitioner-site-oh-mysql
    tier: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-practitioner-site-oh
  labels:
    app: practitioner-site-oh-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: practitioner-site-oh-mysql-depl
  labels:
    app: practitioner-site-oh-mysql
spec:
  selector:
    matchLabels:
      app: practitioner-site-oh-mysql
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: practitioner-site-oh-mysql
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: ROOT_USER_PASSWORD
        - name: MYSQL_DATABASE
          value: oh
        - name: MYSQL_USER
          value: ensemble
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: ADMIN_USER_PASSWORD
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-practitioner-site-oh-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-practitioner-site-oh-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim-practitioner-site-oh
