apiVersion: v1
kind: Service
metadata:
  name: wp-srv
  labels:
    app: wp
spec:
  ports:
    - port: 80
  selector:
    app: wp
    tier: frontend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp
  labels:
    app: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wp
        tier: frontend
    spec:
      containers:
      - image: wordpress:5.9.3-php7.4-apache
        name: wp
        env:
        - name: WORDPRESS_DB_HOST
          value: wp-mysql-srv
        - name: WORDPRESS_DB_USER
          value: ensemble
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: ADMIN_USER_PASSWORD
        ports:
        - containerPort: 80
          name: wp
        volumeMounts:
        - name: wp-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wp-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
