apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-oh-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-oh
  template:
    metadata:
      labels:
        app: profile-oh
    spec:
      containers:
        - name: profile-oh
          image: ohbiohealth/profile-oh
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: healthnet
            - name: MONGO_SRV
              value: profile-oh-mongo-srv
            - name: IDENTITY_SERVICE_URL
              value: 'http://identity-srv:3000/api/identities'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: profile-oh-srv
spec:
  selector:
    app: profile-oh
  ports:
    - name: profile-oh
      protocol: TCP
      port: 3000
      targetPort: 3000
