#comment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-mongo
  template:
    metadata:
      labels:
        app: profile-mongo
    spec:
      containers:
        - name: profile-mongo
          image: mongo
          volumeMounts:
            - name: mongodb-storage-profile
              mountPath: /data/db
              subPath: profile
      volumes:
        - name: mongodb-storage-profile
          persistentVolumeClaim:
            claimName: mongodb-pv-claim-profile
---
apiVersion: v1
kind: Service
metadata:
  name: profile-mongo-srv
spec:
  selector:
    app: profile-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim-profile
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
