apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
        - name: site
          image: ohbiohealth/site
          env:
            - name: NEXT_PUBLIC_MAILCHIMP_URL
              value: 'https://ensembletechs.us20.list-manage.com/subscribe/post?u=28653a604c74efc74ca707df0&amp;id=043676552b'
            - name: NEXT_PUBLIC_YOUTUBE_PLAYLIST_ITEMS_API
              value: 'https://www.googleapis.com/youtube/v3/playlistItems'
            - name: NEXT_PUBLIC_YOUTUBE_API_KEY
              value: 'AIzaSyC-AJHuRDgssX-2Hu-UsXU8QCnSCPNmKJg'
            - name: NEXT_PUBLIC_YOUTUBE_CHANNELID
              value: PLtmKTJS0Kkqw945sc38zAkI5HEqLGm49i
            - name: NEXT_PUBLIC_CLOUDINARY_CLOUD
              value: 'dqmqirs5h'
            - name: NEXT_PUBLIC_CLOUDINARY_PRESET
              value: 'fppkpzyu'
            - name: NEXT_PUBLIC_ECWID_STOREID
              value: '67812829'
            - name: NEXT_PUBLIC_WORDPRESS_URL
              value: 'https://ohbiohealth.shop'
            - name: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
              value: pk_test_51KNcqvHeckYyuEvC3Fgnh3zPNIJqCwiJyFni34mHmvoBvKDxK19vMtEgxrWTalEwpW1yeGdJp2fbhCUaXKelTMtI00nBHj6EuG
---
apiVersion: v1
kind: Service
metadata:
  name: site-srv
spec:
  selector:
    app: site
  ports:
    - name: site
      protocol: TCP
      port: 3000
      targetPort: 3000
