apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-oh-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site-oh
  template:
    metadata:
      labels:
        app: site-oh
    spec:
      containers:
        - name: site-oh
          image: ohbiohealth/site-oh
          env:
            - name: NEXT_PUBLIC_MAILCHIMP_URL
              value: 'https://ensembletechs.us20.list-manage.com/subscribe/post?u=28653a604c74efc74ca707df0&amp;id=043676552b'
            - name: NEXT_PUBLIC_CLOUDINARY_CLOUD
              value: 'dqmqirs5h'
            - name: NEXT_PUBLIC_CLOUDINARY_PRESET
              value: 'fppkpzyu'
            - name: NEXT_PUBLIC_WORDPRESS_URL
              value: 'https://ensemble-tech.shop'
            - name: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
              value: pk_test_51KNcqvHeckYyuEvC3Fgnh3zPNIJqCwiJyFni34mHmvoBvKDxK19vMtEgxrWTalEwpW1yeGdJp2fbhCUaXKelTMtI00nBHj6EuG
---
apiVersion: v1
kind: Service
metadata:
  name: site-oh-srv
spec:
  selector:
    app: site-oh
  ports:
    - name: site-oh
      protocol: TCP
      port: 3000
      targetPort: 3000
