apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher-depl
spec:
  replicas: 0
  selector:
    matchLabels:
      app: watcher
  template:
    metadata:
      labels:
        app: watcher
    spec:
      containers:
        - name: watcher
          image: ohbiohealth/watcher
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: healthnet
            - name: WATCH_EMAIL
              value: gordon@ensembletechs.com
            - name: EMAIL_HOST
              value: web179.dnchosting.com
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: EMAIL_PASSWORD
            