name: deploy-datalake

on:
  push:
    branches:
      - main
    paths:
      - 'datalake/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: cd datalake && docker build -t ohbiohealth/datalake .
      - run: docker push ohbiohealth/datalake
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ohbiohealth
      - run: kubectl rollout restart deployment datalake-depl
