name: deploy-datalake

on:
  push:
    branches:
      - main
    paths:
      - 'datalake/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: cd datalake && docker build -t ohbiohealth/datalake .
      - run: docker push ohbiohealth/datalake

      - uses: statsig-io/kubectl-via-eksctl@main
        env:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          cluster: ${{ secrets.CLUSTER_NAME }}
        with:
          args: rollout restart deployment datalake-depl
