name: deploy-profile-oh

on:
  push:
    branches:
      - main
    paths:
      - 'profile-oh/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: cd profile-oh && docker build -t ohbiohealth/profile-oh .
      - run: docker push ohbiohealth/profile-oh
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ohbiohealth
      - run: kubectl rollout restart deployment profile-oh-depl
